/* ============================================================
   宿コレクション データ
   ------------------------------------------------------------
   各宿に県(pref)・市町村(city)・緯度(lat)・経度(lng)を保持。
   新しい宿は URL を Claude に渡せば、写真・宿名・場所・座標を
   自動取得してここに追記します。
   ============================================================ */

const HOTELS = [
  { id: "shijima-atami", name: "SHIJIMA ATAMI", pref: "静岡県", city: "熱海市", price: "", lat: 35.096, lng: 139.077, photo: "https://shijima-atami.com/files/images/home/img_openinfo02.webp", url: "https://shijima-atami.com", note: "熱海・2026年8月開業予定。" },
  { id: "muishizen-atami", name: "無為自然-ATAMI-", pref: "静岡県", city: "熱海市", price: "", lat: 35.045, lng: 139.098, photo: "https://www.muishizen-atami.com/wp-content/themes/muishizenatami_prd/images/index/mv01.jpg", url: "https://www.muishizen-atami.com/", note: "熱海・網代。海と森を望む客室温泉露天のリゾート。" },
  { id: "hakone-g", name: "箱根G邸", pref: "神奈川県", city: "箱根町", price: "", lat: 35.246, lng: 139.048, photo: "https://hakone-g.jp/lp/images/kv01.jpg", url: "https://hakone-g.jp/lp/", note: "強羅・2026年10月開業。全室温泉露天風呂、オールインクルーシブ。" },
  { id: "nazuna-hakone-miyanoshita", name: "Nazuna 箱根 宮ノ下", pref: "神奈川県", city: "箱根町", price: "", lat: 35.235, lng: 139.066, photo: "https://www.nazuna.co/wp-content/uploads/2025/03/%E5%A4%96%E8%A6%B301-scaled.jpg", url: "https://www.nazuna.co/property/nazuna-hakone-miyanoshita/", note: "宮ノ下・京町家の意匠。全室露天 or 半露天風呂付き。" },
  { id: "hoshinoya-fuji", name: "星のや富士", pref: "山梨県", city: "富士河口湖町", price: "", lat: 35.5269, lng: 138.7479, photo: "https://media.hoshinoresorts.com/image/authenticated/s--ChRuIbfB--/c_fill,g_auto,h_630,w_1200/f_auto,q_auto/v1744973935/OPG%E5%AF%8C%E5%A3%AB_jp_ukrbaz.png", url: "https://hoshinoresorts.com/ja/hotels/hoshinoyafuji/", note: "富士河口湖・河口湖畔のラグジュアリーグランピング。" },
  { id: "hakone-nica", name: "HAKONE NICA", pref: "神奈川県", city: "箱根町", price: "", lat: 35.256, lng: 139.055, photo: "https://hakone-nica.com/wp-content/uploads/2022/06/27e6984e4eff1011119fdcba79164748.jpg", url: "https://hakone-nica.com/", note: "宮城野・記念日向けのオールインクルーシブな隠れ家。" },
  { id: "bettei-umitomori", name: "別邸 海と森", pref: "千葉県", city: "銚子市", price: "", lat: 35.707, lng: 140.868, photo: "https://www.umitomori.jp/img/top/pic_feature03.jpg", url: "https://www.umitomori.jp/", note: "犬吠埼・全室オーシャンビュー＆露天風呂付き。" },
  { id: "hotel-norm-ao", name: "hotel norm. ao", pref: "山梨県", city: "富士河口湖町", price: "", lat: 35.517, lng: 138.727, photo: "https://static.wixstatic.com/media/5bc0a8_d0c4c254d97d4c0f834cdc6944bad9f0~mv2.jpg/v1/fill/w_800,h_500,al_c,q_85,enc_avif,quality_auto/5bc0a8_d0c4c254d97d4c0f834cdc6944bad9f0~mv2.jpg", url: "https://www.hotel-normao.com/", note: "河口湖・富士山麓のウェルネス特化ラグジュアリー。" },
  { id: "senrinokaze", name: "たてやま温泉 千里の風", pref: "千葉県", city: "館山市", price: "", lat: 34.951, lng: 139.799, photo: "https://www.senrinokaze.jp/top/images/spa01.jpg", url: "https://www.senrinokaze.jp/", note: "館山・平砂浦海岸の眺望温泉リゾート。" },
  { id: "nasu-bettei-kai", name: "那須別邸 回", pref: "栃木県", city: "那須町", price: "", lat: 37.126, lng: 139.978, photo: "https://bettei-kai.jp/assets/imgs/top/about.avif", url: "https://bettei-kai.jp/", note: "那須湯本・2000坪に10室。土着をテーマにした温泉旅館。" },
  { id: "okuyugawara-yui", name: "奥湯河原 結唯", pref: "神奈川県", city: "湯河原町", price: "", lat: 35.1629, lng: 139.06, photo: "https://okuyugawara.jp/wp-content/themes/okuyugawara/images/index/slide_01.jpg", url: "https://okuyugawara.jp/", note: "奥湯河原・一棟貸しの離れと温泉サウナ付き本館。" },
  { id: "sizca", name: "別庭 雫花", pref: "千葉県", city: "館山市", price: "", lat: 34.983, lng: 139.826, photo: "https://sizca.jp/top/images/slide/01.jpg", url: "https://sizca.jp/", note: "館山・全5邸。プライベートサウナ＆温泉露天付きヴィラ。" },
  { id: "kureha", name: "紅葉 -KUREHA-", pref: "栃木県", city: "那須塩原市", price: "", lat: 36.98, lng: 139.76, photo: "https://www.vila-kureha.com/files/index/img01_01.jpg", url: "https://www.vila-kureha.com/", note: "塩原温泉・露天風呂付きラグジュアリーコンドミニアムヴィラ。" },
  { id: "itsukiri", name: "五氣里 -itsukiri-", pref: "千葉県", city: "いすみ市", price: "", lat: 35.2324, lng: 140.3406, photo: "https://itsukiri.com/manage/wp-content/themes/itsukiri/assets/img/top/onsen/photo1.jpg", url: "https://itsukiri.com/", note: "いすみ・里山の黒湯温泉付き一棟貸し古民家＆ヴィラ。" },
  { id: "gorakadan-fuji", name: "強羅花壇 富士", pref: "静岡県", city: "小山町", price: "", lat: 35.363, lng: 138.827, photo: "https://www.gorakadan.com/fuji/wp-content/uploads/2025/07/rooftop-01-main.webp", url: "https://www.gorakadan.com/fuji/", note: "富士山麓・須走。全室スイート仕様の温泉宿。" },
  { id: "fufu-jogashima", name: "ふふ 城ヶ島 海風のしらべ", pref: "神奈川県", city: "三浦市", price: "", lat: 35.135, lng: 139.616, photo: "https://fufujogashima.jp/wordpress/wp-content/themes/jogashima/images/top/room_slide01.jpg", url: "https://fufujogashima.jp/", note: "三浦・城ヶ島。全室オーシャンビュー＆油壺温泉付き。" },
  { id: "bettei-shiki", name: "別邸四季", pref: "栃木県", city: "那須町", price: "", lat: 37.0278, lng: 140.0317, photo: "https://www.privatevilla-nasu.com/wp-content/uploads/slider54/view.jpeg", url: "https://www.privatevilla-nasu.com/", note: "那須・プライベートヴィラ。" },
  { id: "izu-ishinoie", name: "別邸 石の家", pref: "静岡県", city: "伊東市", price: "", lat: 34.8948, lng: 139.0997, photo: "https://www.izu-ishinoie.com/img/20210708183554.jpg", url: "https://www.izu-ishinoie.com/", note: "伊豆高原の宿。" },
  { id: "haku-akazawa", name: "HAKU-AKAZAWA 波空", pref: "静岡県", city: "伊東市", price: "", lat: 34.845, lng: 139.108, photo: "https://haku-resort.com/src/relax.jpg", url: "https://www.haku-resort.com/", note: "伊豆赤沢のリゾート。" },
  { id: "soneka", name: "SONEKA", pref: "北海道", city: "北広島市", price: "", lat: 42.953, lng: 141.4794, photo: "https://soneka-hokkaido.com/release/wp-content/themes/soneka/img/ogp.png", url: "https://soneka-hokkaido.com/", note: "北広島のリゾート。" },
  { id: "sansyuyu", name: "櫻湯 山茱萸", pref: "山形県", city: "南陽市", price: "", lat: 38.0486, lng: 140.171, photo: "https://sansyuyu.jp/images/img_intro.png", url: "https://sansyuyu.jp/", note: "赤湯温泉の宿。" },
  { id: "tokinoyado-sumire", name: "時の宿 すみれ", pref: "山形県", city: "米沢市", price: "", lat: 37.96, lng: 140.18, photo: "https://www.tokinoyado.com/wp-content/themes/sumire2025/assets/img/top/summer_late/mv01.jpg", url: "https://www.tokinoyado.com/", note: "湯の沢温泉の宿。" },
  { id: "fuyonoyado", name: "富士山リゾートログハウス ふようの宿", pref: "山梨県", city: "富士吉田市", price: "", lat: 35.479, lng: 138.7829, photo: "https://fuyonoyado.com/wp-content/uploads/2020/11/site_image.jpg", url: "https://www.fuyonoyado.com/", note: "富士吉田・ログハウスの宿。" },
  { id: "tsumugi", name: "天空の温泉ヴィラ 紬", pref: "山梨県", city: "富士河口湖町", price: "", lat: 35.5283, lng: 138.7365, photo: "https://www.resort-glamping.com/wp-content/uploads/2024/07/suite05.jpg", url: "https://www.resort-glamping.com/accommodation/tsumugi/", note: "河口湖・温泉ヴィラ。" },
  { id: "zenagi", name: "Zenagi", pref: "長野県", city: "南木曽町", price: "", lat: 35.583, lng: 137.603, photo: "https://zen-resorts.com/wp-content/uploads/2021/03/zenagi_hotel_top.jpg", url: "https://zen-resorts.com/", note: "南木曽のラグジュアリーリトリート。" },
  { id: "miyako21", name: "こころをなでる静寂 みやこ", pref: "岐阜県", city: "下呂市", price: "", lat: 35.8088, lng: 137.2488, photo: "https://www.miyako21.co.jp/wp/wp-content/themes/miyako21_wp/img/home/main_slide_01.jpg", url: "https://www.miyako21.co.jp/", note: "下呂温泉の宿。" },
  { id: "anorino", name: "1棟貸切の宿 あのりの", pref: "三重県", city: "志摩市", price: "", lat: 34.3528, lng: 136.8758, photo: "https://www.mie-privatevilla.com/wp-content/uploads/2025/11/top-slide-image01.jpg", url: "https://www.mie-privatevilla.com/", note: "志摩・一棟貸し。" },
  { id: "others-iseshima", name: "Others アザーズ伊勢志摩", pref: "三重県", city: "志摩市", price: "", lat: 34.3082, lng: 136.8188, photo: "https://www.others-iseshima-villa.com/wp-content/uploads/2026/02/others-ex.jpg", url: "https://www.others-iseshima-villa.com/", note: "志摩のヴィラ。" },
  { id: "kisara-oneness", name: "季さらOneness", pref: "三重県", city: "鳥羽市", price: "", lat: 34.49, lng: 136.858, photo: "https://www.villa-iseshima.com/wp-content/uploads/2022/06/kisa_nwrm_6.jpg", url: "https://www.villa-iseshima.com/", note: "鳥羽のヴィラ。" },
  { id: "solavilla", name: "SolaVilla 海テラス南あわじ", pref: "兵庫県", city: "南あわじ市", price: "", lat: 34.293, lng: 134.72, photo: "https://static.wixstatic.com/media/e97211_19ff2c85733c4aca97e41eb9b39d2915~mv2.jpg/v1/fill/w_1200,h_675,al_c,q_85,enc_avif,quality_auto/e97211_19ff2c85733c4aca97e41eb9b39d2915~mv2.jpg", url: "https://www.solavilla.jp/", note: "淡路島・海テラスのヴィラ。" },
  { id: "grand-rouge-yuhigaura", name: "グランルージュ 夕日ヶ浦", pref: "京都府", city: "京丹後市", price: "", lat: 35.66, lng: 134.94, photo: "https://www.kyoto-glamping.com/wp-content/uploads/2022/05/mv_1.jpg", url: "https://www.kyoto-glamping.com/", note: "京丹後・夕日ヶ浦のグランピング。" },
  { id: "kotan-ureshino", name: "枯淡嬉野", pref: "佐賀県", city: "嬉野市", price: "", lat: 33.103, lng: 129.982, photo: "https://goten-resort.jp/kotan-ureshino/files/images/home/img_fv01-pc.webp", url: "https://goten-resort.jp/kotan-ureshino/", note: "嬉野温泉の宿。" },
  { id: "aconcagua-minamiaso", name: "THE ACONCAGUA RESORTS 南阿蘇", pref: "熊本県", city: "南阿蘇村", price: "", lat: 32.872, lng: 130.9939, photo: "https://www.resort-glamping.com/wp-content/uploads/2023/08/aconcagua02.jpg", url: "https://www.resort-glamping.com/accommodation/gp-acon/", note: "南阿蘇のグランピング。" },
  { id: "manden", name: "漫厘 Manden", pref: "大分県", city: "別府市", price: "", lat: 33.294, lng: 131.424, photo: "https://manden.co.jp/wp-content/uploads/2023/07/IMG_6853-scaled.jpg", url: "https://manden.co.jp/", note: "別府・明礬温泉の宿。" },
  { id: "the-village-yufuin", name: "The Village 由布院", pref: "大分県", city: "由布市", price: "", lat: 33.272, lng: 131.36, photo: "https://www.oita-glamping.com/wp-content/uploads/2022/06/mv001.jpg", url: "https://www.oita-glamping.com/", note: "由布院のグランピング。" },
  { id: "kazenohibiki", name: "由布院温泉グランピング 風の響き", pref: "大分県", city: "由布市", price: "", lat: 33.268, lng: 131.36, photo: "https://kazenohibiki.com/wp-content/uploads/2025/05/47E44E5D-7932-4815-9356-156470947348.jpeg", url: "https://kazenohibiki.com/", note: "由布院・温泉グランピング。" },
  { id: "villa-montpetre", name: "Villa montpetre", pref: "鹿児島県", city: "霧島市", price: "", lat: 31.852, lng: 130.86, photo: "https://montpetre.net/img/top/topSlider01.jpg", url: "https://montpetre.net/", note: "霧島のヴィラ。" },
  { id: "shoen-hanare", name: "水車の宿 松苑", pref: "鹿児島県", city: "霧島市", price: "", lat: 31.8919, lng: 130.8274, photo: "https://shoenhanare.com/img/top/main1.jpg", url: "https://shoenhanare.com/", note: "霧島の離れ宿。" },
  { id: "koshikano-onsen", name: "こしかの温泉グランピング", pref: "鹿児島県", city: "霧島市", price: "", lat: 31.873, lng: 130.752, photo: "https://koshikano-onsen.com/assets/img/top/top-img-01.jpg", url: "https://koshikano-onsen.com/", note: "霧島・温泉グランピング。" },
  { id: "bros-resort-kyonan", name: "BROS RESORT KYONAN", pref: "千葉県", city: "鋸南町", price: "", lat: 35.1269, lng: 139.8371, photo: "https://bros-resort.com/assets/hero/fv-sequence/20260526_032-2560.jpg", url: "https://bros-resort.com/", note: "鋸南・海を望む一棟貸しサウナヴィラ。2026年開業。" },
  { id: "otowanomori", name: "葉山ホテル音羽ノ森", pref: "神奈川県", city: "横須賀市", price: "", lat: 35.238, lng: 139.583, photo: "https://otowanomori.jp/files/images/home/rooms_slider1.jpg", url: "https://otowanomori.jp/", note: "葉山・秋谷。全室オーシャンビューバスのリゾートホテル。" },
  { id: "shinra-tateyama", name: "THE SHINRA 館山", pref: "千葉県", city: "館山市", price: "", lat: 34.985, lng: 139.828, photo: "https://www.shinra-chiba.com/tateyama/rooms/images/img_bettei01.jpg", url: "https://www.shinra-chiba.com/tateyama/", note: "たてやま温泉・全室露天風呂付き大人のラグジュアリーリゾート。" },
  { id: "shinra-yoro", name: "SHINRA YORO VALLEY", pref: "千葉県", city: "大多喜町", price: "", lat: 35.222, lng: 140.145, photo: "https://www.shinra-chiba.com/yoro/top/images/slide_top/01.jpg", url: "https://www.shinra-chiba.com/yoro/", note: "養老渓谷・渓谷に溶け込む黒湯温泉リゾート。2025年開業。" },
  { id: "suiko-atagawa", name: "伊豆リトリート 熱川粋光", pref: "静岡県", city: "東伊豆町", price: "", lat: 34.813, lng: 139.070, photo: "https://suiko.by-onko-chishin.com/wp-content/uploads/2026/01/025A3014-scaled.jpeg", url: "https://suiko.by-onko-chishin.com/", note: "熱川温泉・全16室オーシャンビュー源泉かけ流し露天風呂付き。2025年11月開業。" },
  { id: "origami-minamiaso", name: "ORIGAMI MINAMIASO", pref: "熊本県", city: "南阿蘇村", price: "", lat: 32.88, lng: 131.03, photo: "https://origami-experience.com/wp-content/uploads/2025/11/DSC09384-3.jpg", url: "https://origami-experience.com/", note: "阿蘇カルデラを望む一棟貸しの宿。" }
];
